
# docker-compose.prod.yml (Updated to align with single package.json)
version: '3.8'
services:
  principal:
    build:
      context: .
      dockerfile: principal/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  hod:
    build:
      context: .
      dockerfile: hod/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  teacher:
    build:
      context: .
      dockerfile: teacher/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production

  student:
    build:
      context: .
      dockerfile: student/Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
